### ISSUE TITLE
Help with subtitles manifest - PHP

### ISSUE THREAD

**Issue by nbvesk** [Stremio/stremio-php-addon-example#1]
Can someone help me edit manifest.php to load subtitles in my add-on?

The code:

$manifest = new stdClass();
	$manifest->id = "com.stremio.phpexample";
	$manifest->version = "1.0.0";
	$manifest->name = "PHP Add-on Example";
	$manifest->description = "Example Add-on made with PHP that server the Big Buck Bunny video.";
	$manifest->resources = array("catalog", "meta", "stream", "subtitles");
	$manifest->types = array("movie", "series");

Please help,

Thanks

**Comment by jaruba** [comment]
This:

```
$manifest->resources = array("catalog", "meta", "stream", "subtitles");
```
is correct, so you don't need anything changed in manifest.php

Make sure to add it to `.htaccess` too:

```
RewriteEngine On
RewriteBase /

RewriteRule ^manifest.json manifest.php

RewriteRule ^catalog/(.*)/(.*)/(.*).json catalogs.php?type=$1&id=$2&extra=$3
RewriteRule ^meta/(.*)/(.*)/(.*).json meta.php?type=$1&id=$2&extra=$3
RewriteRule ^stream/(.*)/(.*)/(.*).json streams.php?type=$1&id=$2&extra=$3
RewriteRule ^subtitles/(.*)/(.*)/(.*).json subtitles.php?type=$1&id=$2&extra=$3

RewriteRule ^catalog/(.*)/(.*).json catalogs.php?type=$1&id=$2
RewriteRule ^meta/(.*)/(.*).json meta.php?type=$1&id=$2
RewriteRule ^stream/(.*)/(.*).json streams.php?type=$1&id=$2
RewriteRule ^subtitles/(.*)/(.*).json subtitles.php?type=$1&id=$2
```

Then create `subtitles.php`

**Comment by jaruba** [comment]
edited my previous comment to correct it

**Comment by nbvesk** [comment]
still dont work,

My files: 

**(subtitles.php)**
$subtitles = getRequestParams();

$jsonPath = dirname(__FILE__) . '/subtitle/' . $subtitles->type . '/' . $subtitles->id . '.json';


**(.htaccess)**
RewriteRule ^subtitles/(.*)/(.*)/(.*).json subtitles.php?type=$1&id=$2&extra=$3

RewriteRule ^subtitles/(.*)/(.*).json subtitles.php?type=$1&id=$2


**(manifest.php)**
$manifest->resources = array("catalog", "meta", "stream", "subtitles");
$manifest->types = array("movie", "series");


**(.json example subtitle file tt6225520.json in folder /subtitle/movie)**
{
  "subtitles": [
    {
      "url": "https://unmade-load.000webhostapp.com/teste.srt",
	  "lang": "fr"
    }	
  ]
}

**what's wrong?**

Stremio error: "Error loading subtitles, Failed to fetch"

many thanks

**Comment by jaruba** [comment]
(.htaccess)
```
RewriteRule ^subtitles/(.)/(.)/(.*).json subtitles.php?type=$1&id=$2&extra=$3

RewriteRule ^subtitles/(.)/(.).json subtitles.php?type=$1&id=$2
```

why `(.)` instead of `(.*)`?

when do u see that error? when u start the video playback? or when u selected the subtitle in the subtitle list?

**Comment by nbvesk** [comment]
Hi,
Error when i start the video playback, (i disable opensubtitles addon, but I think it's not related).

RewriteRule fixed, but still error...

**Add one more file to see: (stream json file: /stream/movie/tt6225520.json)**

{
  "streams": [
    {
      "availability": 1,
	  "name": "MovieAdd-on",
	  "title": "1080p Full HD",
	  "subtitlesExclusive": "true",
      "infoHash": "885fdc8d5d92cabf8d799294236848b4c3dc5da8"
    },
	{
      "availability": 1,
	  "name": "MovieAdd-on",
	  "title": "720p HD",
	  "subtitlesExclusive": "true",
      "infoHash": "18a86559d5c21a72509bc4f0f7aabdc87517e277"
    },
    {
      "availability": 1,
	  "name": "MovieAdd-on",
	  "title": "480p SD",
      "infoHash": "b94333a44a319258891de0f546ef4bc0020bb944"
    }	
  ]
}


Please, help!

Thanks

**Comment by jaruba** [comment]
That's very strange, everything looks alright to me, if u can give me a url to ur add-on, i can check it tonight or maybe tomorrow, I'm at a b-day party now and can't test atm.

**Comment by nbvesk** [comment]
Sure,
Visit: https://unmade-load.000webhostapp.com
Install Add-on and download .zip files (.php manifest, etc...)

Test with movie "T-34", imdb id: tt8820590

Give me feedback, when u see the files,
Thanks

**Comment by nbvesk** [comment]
Hi,

News?

thanks

**Comment by jaruba** [comment]
Ok, I managed to get this working..

`.htaccess` looks like this:
```
RewriteEngine On
RewriteBase /

RewriteRule ^manifest.json manifest.php

RewriteRule ^catalog/(.*)/(.*)/(.*).json catalogs.php?type=$1&id=$2&extra=$3 [B]
RewriteRule ^meta/(.*)/(.*)/(.*).json meta.php?type=$1&id=$2&extra=$3 [B]
RewriteRule ^stream/(.*)/(.*)/(.*).json streams.php?type=$1&id=$2&extra=$3 [B]
RewriteRule ^subtitles/(.*)/(.*)/(.*).json subtitles.php?type=$1&id=$2&extra=$3 [B]

RewriteRule ^catalog/(.*)/(.*).json catalogs.php?type=$1&id=$2
RewriteRule ^meta/(.*)/(.*).json meta.php?type=$1&id=$2
RewriteRule ^stream/(.*)/(.*).json streams.php?type=$1&id=$2
RewriteRule ^subtitles/(.*)/(.*).json subtitles.php?type=$1&id=$2
```

`manifest.php` includes:
```
$manifest->resources = array("catalog", "meta", "stream", "subtitles");
$manifest->idPrefixes = array("tt");
```

`subtitles.php` looks like this:
```
<?php

	include 'helpers.php';

	// get request parameters
	$subtitles = getRequestParams();

	// returns $subtitles->type , $subtitles->id and (if applicabale) $subtitles->extra

	// we will not go into the details of using a database, instead we will serve JSON files located at: 
	// "./subtitles/" . $subtitles->type . "/" . $subtitles->extra->videoId . ".json"
	// ex: "./subtitles/movie/BigBuckBunny.json"

	if ($subtitles->extra && $subtitles->extra->videoId) {
		$jsonPath = dirname(__FILE__) . '/subtitles/' . $subtitles->type . '/' . $subtitles->extra->videoId . '.json';
	}

	if ($jsonPath) {

//		file exists

//		enable CORS and set JSON Content-Type
		setHeaders();

//		respond with json file from file system
		echo file_get_contents($jsonPath);

	} else {

//		respond with 404 page
		page404();

	}

?>
```

`subtitles/movies/tt8820590.json` looks like this:
```
{
  "subtitles": {
    "all": [
      {
        "url": "https://unmade-load.000webhostapp.com/subtitle_srt_test.srt",
        "lang": "fr"
      },
      {
        "url": "https://mkvtoolnix.download/samples/vsshort-en.srt",
        "lang": "en"
      }
    ]
  }
}
```

**Comment by jaruba** [comment]
Oh, and you will also need to make these changes to `helpers.php`: 
https://github.com/Stremio/stremio-php-addon-example/commit/50ba8d6c666e87f09ecd73b000efeab6afbd5348
https://github.com/Stremio/stremio-php-addon-example/commit/5c3506e2c74458c0d90d7a31b534e5d5cd151acd

**Comment by nbvesk** [comment]
Works perfect... Many thanks :)

**Comment by nbvesk** [comment]
You should add this in the php-addon example... Again, many thanks...

**Comment by jaruba** [comment]
I think there's a bigger issue here, someone else tested this and says that IMDB IDs get subtitles from other add-ons only if the Open Subtitles add-on is disabled

This issue is already reported at Stremio.

**Comment by jaruba** [comment]
Ok, it seems like the issue here might be with setting `idPrefixes` globally in the manifest, if we set the `idPrefixes` in the `resources`, it should work, but I haven't personally tested this.

So, changing `manifest.php` to the following code might correct this issue.

```
	$catalogRes = new stdClass();
	$catalogRes->name = "catalog";
	$catalogRes->type = "movie";
	$catalogRes->idPrefixes = array("tt");

	$metaRes = new stdClass();
	$metaRes->name = "meta";
	$metaRes->type = "movie";
	$metaRes->idPrefixes = array("tt");

	$streamRes = new stdClass();
	$streamRes->name = "stream";
	$streamRes->type = "movie";
	$streamRes->idPrefixes = array("tt");

	$subtitlesRes = new stdClass();
	$subtitlesRes->name = "subtitles";
	$subtitlesRes->type = "movie";

	$manifest->resources = array($catalogRes, $metaRes, $streamRes, $subtitlesRes);
	$manifest->types = array("movie");
```

**Comment by jaruba** [comment]
I removed a comment because it was wrong, there is indeed a bug here, if the Open Subtitles add-on is installed first, then other subtitles add-ons won't work, if you disable the Open Subtitles add-on, then restart Stremio, install your add-on first, then the Open Subtitles add-on, your subtitles add-on will work.

Unfortunately this is a Stremio bug that won't be fixed very soon.
