### ISSUE TITLE
Subdomain dont work !?

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-php-addon-example#2]
I have an addon script with the following htaccess:

RewriteEngine On
#RewriteBase /

RewriteRule ^manifest.json manifest.php

RewriteRule ^catalog/(.)/(.)/(.).json catalogs.php?type=$1&id=$2&extra=$3 [B]
RewriteRule ^meta/(.)/(.)/(.).json meta.php?type=$1&id=$2&extra=$3 [B]
RewriteRule ^stream/(.)/(.)/(.*).json streams.php?type=$1&id=$2&extra=$3 [B]

RewriteRule ^catalog/(.)/(.).json catalogs.php?type=$1&id=$2
RewriteRule ^meta/(.)/(.).json meta.php?type=$1&id=$2
RewriteRule ^stream/(.)/(.).json streams.php?type=$1&id=$2

When I use my URL like this, the system recognizes the URL and the link to the plugin:
https://domain.com/stremio/plugin/manifest.json

But when I use this URL, it is not recognized, why?
https://plugin.domain.com/manifest.json

**Comment by jaruba** [comment]
This is not an issue with this example project.. you should google for `.htaccess` configuration requirements: https://stackoverflow.com/questions/10642426/htaccess-rewrite-subdomain-to-directory
