### ISSUE TITLE
Does not work when hosted

### ISSUE THREAD

**Issue by coalexcool** [Stremio/stremio-php-addon-example#3]
I tried to host the code that is here on github and it doesn't work.
It only works locally.
I get an error saying, "Response not recognized as an add-on or a collection."
What I don't understand is how is it possible that it works locally, while the same hosted code does not.

**Comment by coalexcool** [comment]
This is the link to manifest.json file https://stremon.000webhostapp.com/manifest,json

**Comment by jaruba** [comment]
@coalexcool it works fine for me from your link.. maybe you forgot to uninstall the local addon before installing the one that is hosted?

btw, you are using `,` instead of `.` in your link, it should be `https://stremon.000webhostapp.com/manifest.json`

what platform are you testing on?

**Comment by coalexcool** [comment]
Thanks for the reply, unfortunately I am a bit blind and I think I inadvertently made a typo (I have been with this problem for a good half hour🤣)
